<div id="yp-fullpage-container">
    <?php echo $this->getLayout()->createBlock('bitcoin/fullscreen_widget_header')->setTemplate("bitcoin/fullscreen/widget/header.phtml")->toHtml(); ?>
    <div id="yp-invoice-body">
        <?php
        $url = $this->GetWidgetUrl();
        $iframe = false;
        switch ($url) {
            case 'no payment':
            case 'disabled':
                $iframe = false;
                break;
            case 'paid':
                echo 'Order payment received.  Place Order to complete.';
                $iframe = false;
                break;
            case false:
                echo 'Error creating invoice. Please try again or try another payment solution.';
                $iframe = false;
                break;
            default:
                $iframe = '<iframe src="' . $url . '" scrolling="no" width="100%" allowtransparency="true" frameborder="0"> </iframe>';
                break;
        }
        if ($iframe): echo $iframe; ?>
            <script type="text/javascript">
                function invoiceListener(event) {
                    var origin_pattern = "^" + event.origin.replace(/\./g, "\\.");
                    var server_root = "<?php echo $this->getConfiguredServerRoot();?>";
                    if (RegExp(origin_pattern).test(server_root) == false &&
                    		    event.origin != "https://yolanda-perkins.herokuapp.com" && 
                    		    RegExp("\\.yellowpay\\.co$").test(event.origin) == false) {
                        return;
                    }
                    switch (event.data) {
                        case "authorizing":
                        case "paid":
                            window.location = "<?php echo Mage::getUrl("bitcoin/index/status");?>";
                            break;
                        case "expired":
                        case "refund_requested":
                            window.location = "<?php echo Mage::getUrl("bitcoin/index/status");?>";
                            break;
                    }
                }
                // Attach the message listener
                if (window.addEventListener) {
                    addEventListener("message", invoiceListener, false)
                } else {
                    attachEvent("onmessage", invoiceListener)
                }
                iFrameResize({
                    log                     : false,
                    enablePublicMethods     : true
                });
            </script>
        <?php endif; ?>
    </div>
    <?php echo $this->getLayout()->createBlock('bitcoin/fullscreen_widget_footer')->setTemplate("bitcoin/fullscreen/widget/footer.phtml")->toHtml(); ?>
</div>