<div id="yp-fullpage-header" class="clearfix">
    <div class="yp-header-logo">
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img
                src="<?php echo $this->getLogoSrc() ?>" class="logo-img" alt="<?php echo $this->getLogoAlt() ?>"/></a>
    </div>
    <div class="yp-header-title"><span><?php echo $this->__("Your Bitcoin Invoice"); ?></span></div>
</div>