<?php
$url = $this->GetWidgetUrl();
$iframe = false;
switch ($url) {
    case 'nopayment':
    case 'disabled':
        break;
    case 'paid':
        echo 'Order payment received.  Place Order to complete.';
        break;
    case false:
        echo 'Error creating invoice. Please try again or try another payment solution.';
        break;
    default:
        $iframe = '<iframe src="' . $url . '" style="width:500px; height:215px; overflow:hidden; border:none; margin:auto; display:block;" scrolling="no" allowtransparency="true" frameborder="0"> </iframe>';
        break;
}
if ($iframe):
    echo $iframe;
    $quoteId = $this->GetQuoteId();
    $url = Mage::getUrl('bitcoin/index/ipn/');
    ?>
<script type="text/javascript">
     function invoiceListener(event) {
        if (event.origin !== "https://yolanda-perkins-stage.herokuapp.com/") {
          alert("Received message from unexpected domain: " + event.origin);
          return;
        }
        if (event.data == "unconfirmed") {
            buttons = $$("button.btn-checkout");
            buttons.each(function(btn) { btn.click(); })
         }
      }
      // Attach the message listener
      if (window.addEventListener) {
        addEventListener("message", invoiceListener, false)
      } else {
        attachEvent("onmessage", invoiceListener)
      }
</script> 
<?php endif; ?>
