<?php
$url = $this->GetWidgetUrl();
$iframe = false;
switch ($url) {
    case 'no payment':
    case 'disabled':
        $iframe = false;
        break;
    case 'paid':
        echo 'Order payment received.  Place Order to complete.';
        $iframe = false;
        break;
    case false:
        echo 'Error creating invoice. Please try again or try another payment solution.';
        $iframe = false;
        break;
    default:
        $iframe = '<iframe src="' . $url . '" style="width:500px; height:255px; overflow:hidden; border:none; margin:auto; display:block;" scrolling="no" allowtransparency="true" frameborder="0"> </iframe>';
        break;
}
if ($iframe): echo $iframe; ?>
    <script type="text/javascript">
        function invoiceListener(event) {
            var origin_pattern = "^" + event.origin.replace(/\./g, "\\.");
            var server_root = "<?php echo $this->getConfiguredServerRoot();?>";
            if (RegExp(origin_pattern).test(server_root) == false &&
            	    event.origin != "https://yolanda-perkins.herokuapp.com" && 
            		    RegExp("\\.yellowpay\\.co$").test(event.origin) == false) {
            	    return;
            }

            switch (event.data) {
                case "authorizing":
                    buttons = $$("button.btn-checkout");
                    buttons.each(function (btn) {
                        btn.click();
                    })
                    break;
                case "expired":
                case "refund_requested":
                    break;
                default:
                    alert("unknown order status :" + event.data);
                    break;
            }
        }
        // Attach the message listener
        if (window.addEventListener) {
            addEventListener("message", invoiceListener, false)
        } else {
            attachEvent("onmessage", invoiceListener)
        }
    </script>
<?php endif; ?>
