<?php
if(Mage::helper("bitcoin")->isFullScreen()):?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
                <?php echo $this->__("After selecting this payment option and placing your order, you will be redirected to a full page invoice to complete the payment");?>
            </div>
        </li>
    </ul>
<?php endif; ?>