<!-- Yellow Logo -->
<div id="bitcoin">
    <img src="<?php echo $this->getSkinUrl('images/bitcoin/bitcoin_accepted.png', array('_secure' => true)); ?>"
         alt="<?php echo Mage::helper('bitcoin')->__('Yellow Bitcoin') ?>" class="v-middle" style="height:35px;"/>
    <span style="margin-top: 6px;">
        &nbsp;<?php //echo Mage::helper('bitcoin')->__('Powered By Yellow'); ?>
        <small>
            <a href="<?php echo "http://shubitcoin.com/"; ?>" target="_blank">
                <?php echo Mage::helper('bitcoin')->__('What is Bitcoin ?'); ?>
            </a>
        </small>
    </span>
</div>
<!-- Yellow Logo -->
