<!-- Yellow Logo -->
<div id="bitcoin" style="float: left;">
    <img src="<?php echo $this->getSkinUrl('images/bitcoin/bitcoin_accepted.png', array('_secure' => true)); ?>"
         alt="<?php echo Mage::helper('bitcoin')->__('Yellow Bitcoin') ?>" class="v-middle"/>
    <span style="margin-top: 6px;">
        &nbsp;<?php echo Mage::helper('bitcoin')->__('Powered By Yellow'); ?>
        <small>
            <a href="<?php echo "http://shubitcoin.com/"; ?>">
                <?php echo Mage::helper('bitcoin')->__('What is Bitcoin ?'); ?>
            </a>
        </small>
    </span>
</div>
<!-- Yellow Logo -->
